POST http://localhost:5000/v1/api/users
Content-Type: application/json

{
    "firstname":"bless",
    "lastname":"his",
    "email":"b@gmail.com",
    "DOB":"2022-12-12",
    "password":"bless123"

}
###
POST http://localhost:5000/v1/api/auth/login
Content-Type: application/json

{
    
    "email":"b@gmail.com",
    "password":"bless123"

}

